name: Build Extension with Node.js

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Chrome extension
        run: npm run build

      - name: Upload Chrome extension
        uses: actions/upload-artifact@v4
        with:
          name: bys-chrome-${{ github.sha }}
          path: dist

      - name: Build Firefox extension
        run: npm run build:firefox -- --skip-build

      - name: Upload Firefox extension
        uses: actions/upload-artifact@v4
        with:
          name: bys-firefox-${{ github.sha }}
          path: dist
